FROM --platform=linux/amd64 ghcr.io/astral-sh/uv:0.12.17@sha256:10787c682e4184e4f290de1171fd4703dc63de99221f10fe1c99002ce7fa9acc AS uv

FROM --platform=linux/amd64 python:3.12-slim@sha256:44ff437bba879d4941b710a369a8f19266aea34b29002807f0c487fabc9eec9b AS build

WORKDIR /app

COPY --from=uv /uv /uvx /bin/
COPY pyproject.toml uv.lock /app/
RUN uv sync --locked --no-install-project --no-dev

FROM --platform=linux/amd64 python:3.12-slim@sha256:44ff437bba879d4941b710a369a8f19266aea34b29002807f0c487fabc9eec9b

WORKDIR /app

COPY --from=build /app/.venv /app/.venv

COPY common /app/common
COPY predictor/server.py /app/predictor/server.py

ENV PATH=/app/.venv/bin:$PATH
ENV PYTHONPATH=/app
ENV MODEL_NAME=image-mmd-model
ENV PORT=8080

EXPOSE 8080

USER 1001
ENTRYPOINT ["python", "/app/predictor/server.py"]
